// Mocks generated by Mockito 5.3.2 from annotations
// in my_app/test/model/ingredient_factory_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_app/data_access/database_interactor.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DatabaseInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseInteractor extends _i1.Mock
    implements _i2.DatabaseInteractor {
  @override
  _i3.Future<dynamic> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> write(
    String? className,
    String? id,
    String? encodedJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            className,
            id,
            encodedJson,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  String read(
    String? className,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [
            className,
            id,
          ],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.Future<dynamic> delete(
    String? className,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            className,
            id,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  List<String> readList(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #readList,
          [prefix],
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);
  @override
  String export() => (super.noSuchMethod(
        Invocation.method(
          #export,
          [],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.Future<dynamic> import(String? data) => (super.noSuchMethod(
        Invocation.method(
          #import,
          [data],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
